name: Best value beer update

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the script every day at midnight
  workflow_dispatch:  # This is for manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py  # Replace with your actual script

    - name: Commit and push if it's changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        message=$(git status --porcelain)
        if [ -n "${message}" ]; then
          git commit -m "Update data" -a
          git push
        fi
